### PR TITLE
[RW-893] Style message when feedback is submitted

### PR DESCRIPTION
**Pull request by rupl**
# RW-893

⚠️ I unfortunately couldn't debug a major problem before the week ended. PR marked draft. Sorry. ⚠️ 

Now when feedback is submitted, the message that returns looks like a standard Drupal message. The scrolling effect is also disabled for feedback submissions, making it more visible as well.

The show-stopper bug here is that somehow the main submit button will fire N+1 events off after using the feedback mechanism. I tested by submitting feedback more than once, and noted that they always add up to the total number of times you clicked any submit button plus one for the "real" submit button. Here's a screenshot with `console.log` into each function attached to the respective buttons. I took the following actions:

- Press <kbd>Ask</kbd>
- Press <kbd>Submit Feedback</kbd>
- Press <kbd>Ask</kbd>

Screenshot 2024-03-01 at 16 18 59

If you submit feedback twice, it'll show the question three times, 3x feedback = 4x question, etc.

I tried inserting `ev.stopPropagation()` in the feedback button, but the bubbling seems to happen inside Drupal code as best I can tell. The <kbd>Ask</kbd> button seemingly gets clicked each time I click the feedback button. It's really hard to screenshot since it's so momentary, but look for the <kbd>Ask</kbd> button to briefly look washed out (like in the screenshot). Additionally, the `chatSend()` isn't getting invoked when <kbd>Submit Feedback</kbd> gets pressed.. they all pile up and fire simultaneously once you finally click <kbd>Ask</kbd> again.

### CODE REVIEW

**Comment by orakili** [comment]
@rupl See https://github.com/UN-OCHA/ocha_ai/pull/9 for a fix.

**Review by orakili — COMMENTED** [review]
The feedback message after clicking submit feedback is properly styled. 

However the chat doesn't scroll to the bottom when expanding the "Please give feedback" details or when the "Feedback submitted" message appears.

I wonder, if mutation observers could not be used to control when to scroll:
- one observer on attributes -> `open` for feedback details --> scroll to bottom of feedback
- one observer on added elements (ex: feedback message --> scroll to bottom of feedback)

**Review by orakili — APPROVED** [review]
@rupl Ok, then good to go for me. After it's merged, could create a new release?

**Comment by rupl** [comment]
Yup a new release would be good 👍🏼

**Pull request merged**
